index:
   path: /
   controller: App\Controller\DefaultController::index

brand_show:
  # Matches /brand/*
  # but not /brand/slug/extra-part
  path:     /brand/{slug}
  controller: App\Controller\BrandsController::show

create_review:
  # Matches /review/*
  # but not /review/slug/extra-part
  path:     /review/{slug}
  controller: App\Controller\ReviewsController::newReview

brand_search:
  # Matches /search exactly
  path:     /search
  controller: App\Controller\BrowseController::search

brands_create:
  # Matches /brands_create exactly
  path:     /brands_create
  controller: App\Controller\BrandsController::createBrand

search_page:
  # Matches /search_page exactly
  path:     /search_page
  controller: App\Controller\BrowseController::searchPage
